export const SERVICE_URL = {
  getVideoDetails: {
    url: `https://www.googleapis.com/youtube/v3/videos?key=${import.meta.env.VITE_API_KEY}&`,
    method: "get",
    query: true,
    tag: "getVideoInfo",
  },
  getChannelDetails: {
    url: `https://www.googleapis.com/youtube/v3/channels?key=${import.meta.env.VITE_API_KEY}&`,
    method: "get",
    query: true,
    tag: "getChannelInfo",
  },
  getVideoComments: {
    url: `https://www.googleapis.com/youtube/v3/commentThreads?key=${import.meta.env.VITE_API_KEY}&`,
    method: "get",
    query: true,
    tag: "getVideoComments",
  },
  getVideoRatings: {
    url: `https://www.googleapis.com/youtube/v3/videos/getRating?key=${import.meta.env.VITE_API_KEY}&`,
    method: "get",
    query: true,
    tag: "getVideoRating",
    authorization: true,
  },
  addVideoRating: {
    url: `https://www.googleapis.com/youtube/v3/videos/rate?key=${import.meta.env.VITE_API_KEY}`,
    method: "POST",
    params: true,
    tag: "addVideoRating",
    authorization: true,
  },
  getSubscription: {
    url: `https://www.googleapis.com/youtube/v3/subscriptions?key=${import.meta.env.VITE_API_KEY}&`,
    mehod: "get",
    query: true,
    tag: "getSubscription",
    authorization: true,
  },
  addSubscription: {
    url: `https://www.googleapis.com/youtube/v3/subscriptions?key=${import.meta.env.VITE_API_KEY}`,
    method: "POST",
    params: true,
    tag: "addAuthorization",
    authorization: true,
  },
  removeSubsciption: {
    url: `https://www.googleapis.com/youtube/v3/subscriptions?key=${import.meta.env.VITE_API_KEY}`,
    method: "DELETE",
    params: true,
    tag: "removeSubsciption",
    authorization: true,
  },
  addVideoComments: {
    url: `https://www.googleapis.com/youtube/v3/commentThreads?key=${import.meta.env.VITE_API_KEY}`,
    method: "post",
    params: true,
    tag: "addVideoComments",
    authorization: true,
  },
  addCommentReply: {
    url: `https://www.googleapis.com/youtube/v3/comments?key=${import.meta.env.VITE_API_KEY}`,
    method: "post",
    params: true,
    tag: "addVideoComments",
    authorization: true,
  },
  getSearch: {
    url: `https://www.googleapis.com/youtube/v3/search?key=${import.meta.env.VITE_API_KEY}&`,
    method: "get",
    query: true,
    tag: "searchVideos",
  },
  getAllProducts: { url: "/getproducts", method: "GET", tag: "loadProducts" },
  getProductsByCategory: { url: "/getproductbycategory", method: "GET", query: true, tag: "loadProducts" },
  getProductsBySubCategory: { url: "/getproductbysubcategory", method: "GET", query: true, tag: "loadProducts" },
  getCategories: { url: "/getCategories", method: "GET", query: true, tag: "category" },
};

export const AXIOS_STATUS = {
  ERR_NETWORK: {
    title: "Network Error",
    description: "Seems like you are not connected to network, Please connect to network",
  },
  ERR_CANCELED: {
    title: "Request Cancelled",
    description: "Request is Cancelled by the Client",
  },
  ERR_BAD_OPTION_VALUE: {},
  ERR_BAD_OPTION: {},
  ECONNABORTED: {},
  ETIMEDOUT: {},
  ERR_FR_TOO_MANY_REDIRECTS: {},
  ERR_DEPRECATED: {},
  ERR_BAD_RESPONSE: {},
  ERR_BAD_REQUEST: {},
  ERR_NOT_SUPPORT: {},
  ERR_INVALID_URL: {},
};
